version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install -r requirements.txt
    - mkdocs build --strict -d $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: requirements.txt

formats:
  - htmlzip